### ISSUE TITLE
NewFsVmView$CpNamePanel.class can not be decompiled by CFR due to issue in wrapper

### ISSUE THREAD

**Issue by judovana** [pmikova/java-runtime-decompiler#96]
String decompiledString = readStringFromFile(decompiledFiles.get(0));

```
Caused by: java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
	at java.base/java.util.Objects.checkIndex(Objects.java:372)
	at java.base/java.util.ArrayList.get(ArrayList.java:459)
	at CfrDecompilerWrapper.cfr(CfrDecompilerWrapper.java:88)
	at CfrDecompilerWrapper.decompile(CfrDecompilerWrapper.java:52)

```

**Comment by AurumTheEnd** [comment]
Fixed in 66090ed7702de48ad60801caf0eb7cfcb2e64be3.
